services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: upwork
      POSTGRES_PASSWORD: upwork
      POSTGRES_DB: upwork
    ports:
      - '5433:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
